- name: 3.1.1 Ensure IP forwarding is disabled (IPv6)
  lineinfile:
    path: /etc/sysctl.d/CIS.conf
    line: 'net.ipv6.conf.all.forwarding = 0'
    create: yes

- name: 3.2.1 Ensure source routed packets are not accepted (IPv6)
  lineinfile:
    path: /etc/sysctl.d/CIS.conf
    line: 'net.ipv6.conf.all.accept_source_route = 0'
    create: yes

- name: 3.2.1 Ensure source routed packets are not accepted (IPv6)
  lineinfile:
    path: /etc/sysctl.d/CIS.conf
    line: 'net.ipv6.conf.default.accept_source_route = 0'
    create: yes