- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install cramfs /bin/true
    create: yes

- name: 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install freevxfs /bin/true
    create: yes

- name: 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install jffs2 /bin/true
    create: yes

- name: 1.1.1.4 Ensure mounting of hfs filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install hfs /bin/true
    create: yes

- name: 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install hfsplus /bin/true
    create: yes

- name: 1.1.1.6 Ensure mounting of squashfs filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install squashfs /bin/true
    create: yes

- name: 1.1.1.7 Ensure mounting of udf filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install udf /bin/true
    create: yes

- name: 1.1.1.8 Ensure mounting of FAT filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: install vfat /bin/true
    create: yes

- name: 1.4.1 Ensure permissions on bootloader config are configured
  file:
    path: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: 0600

- name: 1.5.1 Ensure core dumps are restricted
  lineinfile:
    path: /etc/security/limits.d/CIS.conf
    line: '* hard core 0'
    create: yes

- name: 1.5.1 Ensure core dumps are restricted
  lineinfile:
    path: /etc/sysctl.d/CIS.conf
    line: 'fs.suid_dumpable = 0'
    create: yes

- name: 1.5.3 Ensure address space layout randomization (ASLR) is enabled
  lineinfile:
    path: /etc/sysctl.d/CIS.conf
    line: 'kernel.randomize_va_space = 2'
    create: yes

- name: 1.6.3 Ensure SELinux or AppArmor are installed
  apt:
    name: apparmor-profiles
    state: present

- name: 1.6.3 Ensure SELinux or Apparmor are installed
  file:
    path: /etc/default/grub.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: 1.6.3 Ensure SELinux or AppArmor are installed
  when:
    - ansible_facts['distribution'] == "Debian"
    - ansible_facts['distribution_major_version'] is version("10", "lt")
  copy:
    content: 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT apparmor=1 security=apparmor"'
    dest: /etc/default/grub.d/apparmor.cfg
    owner: root
    group: root
    mode: 0644

- name: 1.6.3 Ensure SELinux or AppArmor are installed
  command:
    cmd: /usr/sbin/update-grub

- name: 1.7.1.2 Ensure local login warning banner is configured properly
  copy:
    content: "{{ logon_banner }}"
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644

- name: 1.7.1.3 Ensure remote login warning banner is configured properly
  copy:
    content: "{{ logon_banner }}"
    dest: /etc/issue.net
    owner: root
    group: root
    mode: 0644

- name: 1.7.1.4 Ensure permissions on /etc/motd are configured
  file:
    path: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: 1.7.1.5 Ensure permissions on /etc/issue are configured
  file:
    path: /etc/issue
    owner: root
    group: root
    mode: 0644

- name: 1.7.1.6 Ensure permissions on /etc/issue.net are configured
  file:
    path: /etc/issue.net
    owner: root
    group: root
    mode: 0644
