---

- name: Install Unattended Upgrades
  apt: name={{ item }} state=present
  with_items:
    - debconf-utils
    - unattended-upgrades

- name: Enable Unattended Upgrades (Automatic Security Updates)
  debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: true
    vtype: boolean
